### ISSUE TITLE
Problemi con Client e Server 

### ISSUE THREAD

**Issue by Valerio1990** [francescofilitti/keZapp-quattro#4]
java.lang.NullPointerException: Cannot invoke "it.iad2.model4.Chat.getNickname()" because "dest" is null
	at it.iad2.serviceImpl4.ServiceImplQuattro.inviaTutti(ServiceImplQuattro.java:61) ~[classes/:na]
	at it.iad2.controller4.ContollerQuattro.inviaTutti(ContollerQuattro.java:31) ~[classes/:na]

**Comment by Valerio1990** [comment]
ServiceImplQuattro.inviaTutti(ServiceImplQuattro.java:61)

![2021-03-18 (2)](https://user-images.githubusercontent.com/79707454/111619041-5e0b6e00-87e5-11eb-9340-3b01ea2b6561.png)

**Comment by Valerio1990** [comment]
.ContollerQuattro.inviaTutti(ContollerQuattro.java:31)

![2021-03-18 (3)](https://user-images.githubusercontent.com/79707454/111619285-a7f45400-87e5-11eb-8c27-cd1542a769bb.png)

**Comment by Valerio1990** [comment]
![2021-03-18 (5)](https://user-images.githubusercontent.com/79707454/111619525-fb66a200-87e5-11eb-89aa-186041900577.png)
